// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateEmoji implements pgx.CopyFromSource.
type iteratorForCreateEmoji struct {
	rows                 []CreateEmojiParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateEmoji) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateEmoji) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].UserID,
		r.rows[0].Url,
		r.rows[0].Shortcode,
	}, nil
}

func (r iteratorForCreateEmoji) Err() error {
	return nil
}

func (q *Queries) CreateEmoji(ctx context.Context, arg []CreateEmojiParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"emojis"}, []string{"id", "user_id", "url", "shortcode"}, &iteratorForCreateEmoji{rows: arg})
}
