// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkChannelMembership = `-- name: CheckChannelMembership :execresult
SELECT c.id FROM channels c, server_membership sm WHERE c.id = $1 and c.server_id = sm.server_id and sm.user_id = $2
`

type CheckChannelMembershipParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) CheckChannelMembership(ctx context.Context, arg CheckChannelMembershipParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, checkChannelMembership, arg.ID, arg.UserID)
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
  id, author_id, server_id, channel_id, content, everyone, mentions_users, mentions_channels, attachments
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, author_id, server_id, channel_id, content, everyone, mentions_users, mentions_channels, attachments, created_at, updated_at
`

type CreateMessageParams struct {
	ID               string          `json:"id"`
	AuthorID         string          `json:"author_id"`
	ServerID         string          `json:"server_id"`
	ChannelID        string          `json:"channel_id"`
	Content          json.RawMessage `json:"content"`
	Everyone         bool            `json:"everyone"`
	MentionsUsers    []string        `json:"mentions_users"`
	MentionsChannels []string        `json:"mentions_channels"`
	Attachments      []byte          `json:"attachments"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.AuthorID,
		arg.ServerID,
		arg.ChannelID,
		arg.Content,
		arg.Everyone,
		arg.MentionsUsers,
		arg.MentionsChannels,
		arg.Attachments,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ServerID,
		&i.ChannelID,
		&i.Content,
		&i.Everyone,
		&i.MentionsUsers,
		&i.MentionsChannels,
		&i.Attachments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :execresult
DELETE FROM messages WHERE id = $1 AND author_id = $2
`

type DeleteMessageParams struct {
	ID       string `json:"id"`
	AuthorID string `json:"author_id"`
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteMessage, arg.ID, arg.AuthorID)
}

const getLatestMessagesRead = `-- name: GetLatestMessagesRead :many
SELECT channel_id, last_read_message_id, unread_mention_ids FROM user_channel_read_state WHERE user_id = $1
`

type GetLatestMessagesReadRow struct {
	ChannelID         string      `json:"channel_id"`
	LastReadMessageID pgtype.Text `json:"last_read_message_id"`
	UnreadMentionIds  []byte      `json:"unread_mention_ids"`
}

func (q *Queries) GetLatestMessagesRead(ctx context.Context, userID string) ([]GetLatestMessagesReadRow, error) {
	rows, err := q.db.Query(ctx, getLatestMessagesRead, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestMessagesReadRow
	for rows.Next() {
		var i GetLatestMessagesReadRow
		if err := rows.Scan(&i.ChannelID, &i.LastReadMessageID, &i.UnreadMentionIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestMessagesSent = `-- name: GetLatestMessagesSent :many
SELECT m.id, m.channel_id FROM messages m WHERE channel_id = ANY($1::text[]) ORDER BY created_at DESC LIMIT 1
`

type GetLatestMessagesSentRow struct {
	ID        string `json:"id"`
	ChannelID string `json:"channel_id"`
}

func (q *Queries) GetLatestMessagesSent(ctx context.Context, dollar_1 []string) ([]GetLatestMessagesSentRow, error) {
	rows, err := q.db.Query(ctx, getLatestMessagesSent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestMessagesSentRow
	for rows.Next() {
		var i GetLatestMessagesSentRow
		if err := rows.Scan(&i.ID, &i.ChannelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessage = `-- name: GetMessage :one
SELECT id, author_id, server_id, channel_id, content, everyone, mentions_users, mentions_channels, attachments, created_at, updated_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ServerID,
		&i.ChannelID,
		&i.Content,
		&i.Everyone,
		&i.MentionsUsers,
		&i.MentionsChannels,
		&i.Attachments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessagesFromChannel = `-- name: GetMessagesFromChannel :many
SELECT id, author_id, server_id, channel_id, content, everyone, mentions_users, mentions_channels, attachments, created_at, updated_at FROM messages WHERE channel_id = $1
`

func (q *Queries) GetMessagesFromChannel(ctx context.Context, channelID string) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesFromChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ServerID,
			&i.ChannelID,
			&i.Content,
			&i.Everyone,
			&i.MentionsUsers,
			&i.MentionsChannels,
			&i.Attachments,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveUnreadMessagesState = `-- name: SaveUnreadMessagesState :exec
INSERT INTO user_channel_read_state (user_id, channel_id, last_read_message_id, unread_mention_ids)
SELECT $1, unnest($2::VARCHAR[]), unnest($3::VARCHAR[]), unnest($4::JSONB[])
ON CONFLICT (user_id, channel_id)
DO UPDATE SET 
    last_read_message_id = EXCLUDED.last_read_message_id,
    unread_mention_ids = EXCLUDED.unread_mention_ids,
    updated_at = NOW()
`

type SaveUnreadMessagesStateParams struct {
	UserID             string            `json:"user_id"`
	ChannelIds         []string          `json:"channel_ids"`
	LastReadMessageIds []string          `json:"last_read_message_ids"`
	UnreadMentionIds   []json.RawMessage `json:"unread_mention_ids"`
}

func (q *Queries) SaveUnreadMessagesState(ctx context.Context, arg SaveUnreadMessagesStateParams) error {
	_, err := q.db.Exec(ctx, saveUnreadMessagesState,
		arg.UserID,
		arg.ChannelIds,
		arg.LastReadMessageIds,
		arg.UnreadMentionIds,
	)
	return err
}

const updateMessage = `-- name: UpdateMessage :execresult
UPDATE messages 
SET content = $1, mentions_users = $2, mentions_channels = $3, everyone = $4, updated_at = now()
WHERE id = $5 AND author_id = $6
`

type UpdateMessageParams struct {
	Content          json.RawMessage `json:"content"`
	MentionsUsers    []string        `json:"mentions_users"`
	MentionsChannels []string        `json:"mentions_channels"`
	Everyone         bool            `json:"everyone"`
	ID               string          `json:"id"`
	AuthorID         string          `json:"author_id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateMessage,
		arg.Content,
		arg.MentionsUsers,
		arg.MentionsChannels,
		arg.Everyone,
		arg.ID,
		arg.AuthorID,
	)
}

const updateMessageContent = `-- name: UpdateMessageContent :execresult
UPDATE messages SET content = $1 WHERE id = $2 AND author_id = $3
`

type UpdateMessageContentParams struct {
	Content  json.RawMessage `json:"content"`
	ID       string          `json:"id"`
	AuthorID string          `json:"author_id"`
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateMessageContent, arg.Content, arg.ID, arg.AuthorID)
}

const updateMessageMentionsChannels = `-- name: UpdateMessageMentionsChannels :execresult
UPDATE messages SET mentions_channels = $1 WHERE id = $2 AND author_id = $3
`

type UpdateMessageMentionsChannelsParams struct {
	MentionsChannels []string `json:"mentions_channels"`
	ID               string   `json:"id"`
	AuthorID         string   `json:"author_id"`
}

func (q *Queries) UpdateMessageMentionsChannels(ctx context.Context, arg UpdateMessageMentionsChannelsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateMessageMentionsChannels, arg.MentionsChannels, arg.ID, arg.AuthorID)
}

const updateMessageMentionsUsers = `-- name: UpdateMessageMentionsUsers :execresult
UPDATE messages SET mentions_users = $1 WHERE id = $2 AND author_id = $3
`

type UpdateMessageMentionsUsersParams struct {
	MentionsUsers []string `json:"mentions_users"`
	ID            string   `json:"id"`
	AuthorID      string   `json:"author_id"`
}

func (q *Queries) UpdateMessageMentionsUsers(ctx context.Context, arg UpdateMessageMentionsUsersParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateMessageMentionsUsers, arg.MentionsUsers, arg.ID, arg.AuthorID)
}
