// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WSMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*WSMessage_ChatMessage
	//	*WSMessage_ChannelCreation
	//	*WSMessage_ChannelRemoved
	Content       isWSMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSMessage) Reset() {
	*x = WSMessage{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSMessage) ProtoMessage() {}

func (x *WSMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSMessage.ProtoReflect.Descriptor instead.
func (*WSMessage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *WSMessage) GetContent() isWSMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WSMessage) GetChatMessage() *BroadcastChatMessage {
	if x != nil {
		if x, ok := x.Content.(*WSMessage_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *WSMessage) GetChannelCreation() *BroadcastChannelCreation {
	if x != nil {
		if x, ok := x.Content.(*WSMessage_ChannelCreation); ok {
			return x.ChannelCreation
		}
	}
	return nil
}

func (x *WSMessage) GetChannelRemoved() *BroadcastChannelRemoved {
	if x != nil {
		if x, ok := x.Content.(*WSMessage_ChannelRemoved); ok {
			return x.ChannelRemoved
		}
	}
	return nil
}

type isWSMessage_Content interface {
	isWSMessage_Content()
}

type WSMessage_ChatMessage struct {
	ChatMessage *BroadcastChatMessage `protobuf:"bytes,1,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type WSMessage_ChannelCreation struct {
	ChannelCreation *BroadcastChannelCreation `protobuf:"bytes,2,opt,name=channel_creation,json=channelCreation,proto3,oneof"`
}

type WSMessage_ChannelRemoved struct {
	ChannelRemoved *BroadcastChannelRemoved `protobuf:"bytes,3,opt,name=channel_removed,json=channelRemoved,proto3,oneof"`
}

func (*WSMessage_ChatMessage) isWSMessage_Content() {}

func (*WSMessage_ChannelCreation) isWSMessage_Content() {}

func (*WSMessage_ChannelRemoved) isWSMessage_Content() {}

type UserLinksRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLinksRow) Reset() {
	*x = UserLinksRow{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLinksRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLinksRow) ProtoMessage() {}

func (x *UserLinksRow) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLinksRow.ProtoReflect.Descriptor instead.
func (*UserLinksRow) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *UserLinksRow) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserLinksRow) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UserLinksRow) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UserFactsRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFactsRow) Reset() {
	*x = UserFactsRow{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFactsRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFactsRow) ProtoMessage() {}

func (x *UserFactsRow) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFactsRow.ProtoReflect.Descriptor instead.
func (*UserFactsRow) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *UserFactsRow) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserFactsRow) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UserFactsRow) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName    string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Avatar         *string                `protobuf:"bytes,5,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Banner         *string                `protobuf:"bytes,6,opt,name=banner,proto3,oneof" json:"banner,omitempty"`
	GradientTop    *string                `protobuf:"bytes,7,opt,name=gradient_top,json=gradientTop,proto3,oneof" json:"gradient_top,omitempty"`
	GradientBottom *string                `protobuf:"bytes,8,opt,name=gradient_bottom,json=gradientBottom,proto3,oneof" json:"gradient_bottom,omitempty"`
	About          *string                `protobuf:"bytes,9,opt,name=about,proto3,oneof" json:"about,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Links          []*UserLinksRow        `protobuf:"bytes,11,rep,name=links,proto3" json:"links,omitempty"`
	Facts          []*UserFactsRow        `protobuf:"bytes,12,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *User) GetBanner() string {
	if x != nil && x.Banner != nil {
		return *x.Banner
	}
	return ""
}

func (x *User) GetGradientTop() string {
	if x != nil && x.GradientTop != nil {
		return *x.GradientTop
	}
	return ""
}

func (x *User) GetGradientBottom() string {
	if x != nil && x.GradientBottom != nil {
		return *x.GradientBottom
	}
	return ""
}

func (x *User) GetAbout() string {
	if x != nil && x.About != nil {
		return *x.About
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetLinks() []*UserLinksRow {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *User) GetFacts() []*UserFactsRow {
	if x != nil {
		return x.Facts
	}
	return nil
}

type IncomingChatMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Author           *User                  `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	ServerId         int32                  `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ChannelId        int32                  `protobuf:"varint,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content          []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	MentionsUsers    []int32                `protobuf:"varint,5,rep,packed,name=mentions_users,json=mentionsUsers,proto3" json:"mentions_users,omitempty"`
	MentionsChannels []int32                `protobuf:"varint,6,rep,packed,name=mentions_channels,json=mentionsChannels,proto3" json:"mentions_channels,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IncomingChatMessage) Reset() {
	*x = IncomingChatMessage{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingChatMessage) ProtoMessage() {}

func (x *IncomingChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingChatMessage.ProtoReflect.Descriptor instead.
func (*IncomingChatMessage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *IncomingChatMessage) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *IncomingChatMessage) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *IncomingChatMessage) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *IncomingChatMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *IncomingChatMessage) GetMentionsUsers() []int32 {
	if x != nil {
		return x.MentionsUsers
	}
	return nil
}

func (x *IncomingChatMessage) GetMentionsChannels() []int32 {
	if x != nil {
		return x.MentionsChannels
	}
	return nil
}

type BroadcastChatMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Author           *User                  `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	ServerId         int32                  `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ChannelId        int32                  `protobuf:"varint,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content          []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	MentionsUsers    []int32                `protobuf:"varint,6,rep,packed,name=mentions_users,json=mentionsUsers,proto3" json:"mentions_users,omitempty"`
	MentionsChannels []int32                `protobuf:"varint,7,rep,packed,name=mentions_channels,json=mentionsChannels,proto3" json:"mentions_channels,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BroadcastChatMessage) Reset() {
	*x = BroadcastChatMessage{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastChatMessage) ProtoMessage() {}

func (x *BroadcastChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastChatMessage.ProtoReflect.Descriptor instead.
func (*BroadcastChatMessage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

func (x *BroadcastChatMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BroadcastChatMessage) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *BroadcastChatMessage) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BroadcastChatMessage) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *BroadcastChatMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *BroadcastChatMessage) GetMentionsUsers() []int32 {
	if x != nil {
		return x.MentionsUsers
	}
	return nil
}

func (x *BroadcastChatMessage) GetMentionsChannels() []int32 {
	if x != nil {
		return x.MentionsChannels
	}
	return nil
}

func (x *BroadcastChatMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type BroadcastChannelRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ChannelId     int32                  `protobuf:"varint,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorAddress  string                 `protobuf:"bytes,4,opt,name=actor_address,json=actorAddress,proto3" json:"actor_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastChannelRemoved) Reset() {
	*x = BroadcastChannelRemoved{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastChannelRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastChannelRemoved) ProtoMessage() {}

func (x *BroadcastChannelRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastChannelRemoved.ProtoReflect.Descriptor instead.
func (*BroadcastChannelRemoved) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

func (x *BroadcastChannelRemoved) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BroadcastChannelRemoved) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *BroadcastChannelRemoved) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *BroadcastChannelRemoved) GetActorAddress() string {
	if x != nil {
		return x.ActorAddress
	}
	return ""
}

type BroadcastChannelCreation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId      int32                  `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Users         []int32                `protobuf:"varint,6,rep,packed,name=users,proto3" json:"users,omitempty"`
	Roles         []int32                `protobuf:"varint,7,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	X             int32                  `protobuf:"varint,8,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,9,opt,name=y,proto3" json:"y,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ActorId       string                 `protobuf:"bytes,12,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorAddress  string                 `protobuf:"bytes,13,opt,name=actor_address,json=actorAddress,proto3" json:"actor_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastChannelCreation) Reset() {
	*x = BroadcastChannelCreation{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastChannelCreation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastChannelCreation) ProtoMessage() {}

func (x *BroadcastChannelCreation) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastChannelCreation.ProtoReflect.Descriptor instead.
func (*BroadcastChannelCreation) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *BroadcastChannelCreation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BroadcastChannelCreation) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BroadcastChannelCreation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BroadcastChannelCreation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BroadcastChannelCreation) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *BroadcastChannelCreation) GetUsers() []int32 {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *BroadcastChannelCreation) GetRoles() []int32 {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *BroadcastChannelCreation) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BroadcastChannelCreation) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BroadcastChannelCreation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BroadcastChannelCreation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BroadcastChannelCreation) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *BroadcastChannelCreation) GetActorAddress() string {
	if x != nil {
		return x.ActorAddress
	}
	return ""
}

type BodyChannelCreation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Users         []int32                `protobuf:"varint,6,rep,packed,name=users,proto3" json:"users,omitempty"`
	Roles         []int32                `protobuf:"varint,7,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	X             int32                  `protobuf:"varint,8,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,9,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyChannelCreation) Reset() {
	*x = BodyChannelCreation{}
	mi := &file_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyChannelCreation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyChannelCreation) ProtoMessage() {}

func (x *BodyChannelCreation) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyChannelCreation.ProtoReflect.Descriptor instead.
func (*BodyChannelCreation) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{8}
}

func (x *BodyChannelCreation) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BodyChannelCreation) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *BodyChannelCreation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BodyChannelCreation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BodyChannelCreation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BodyChannelCreation) GetUsers() []int32 {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *BodyChannelCreation) GetRoles() []int32 {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *BodyChannelCreation) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BodyChannelCreation) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type BodyChannelRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ChannelId     int32                  `protobuf:"varint,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyChannelRemoved) Reset() {
	*x = BodyChannelRemoved{}
	mi := &file_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyChannelRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyChannelRemoved) ProtoMessage() {}

func (x *BodyChannelRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyChannelRemoved.ProtoReflect.Descriptor instead.
func (*BodyChannelRemoved) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{9}
}

func (x *BodyChannelRemoved) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *BodyChannelRemoved) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *BodyChannelRemoved) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NewServerCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorAddress  string                 `protobuf:"bytes,2,opt,name=actor_address,json=actorAddress,proto3" json:"actor_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewServerCreated) Reset() {
	*x = NewServerCreated{}
	mi := &file_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewServerCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewServerCreated) ProtoMessage() {}

func (x *NewServerCreated) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewServerCreated.ProtoReflect.Descriptor instead.
func (*NewServerCreated) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{10}
}

func (x *NewServerCreated) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *NewServerCreated) GetActorAddress() string {
	if x != nil {
		return x.ActorAddress
	}
	return ""
}

type Connect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connect) Reset() {
	*x = Connect{}
	mi := &file_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{11}
}

type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{12}
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x01\n" +
	"\tWSMessage\x12@\n" +
	"\fchat_message\x18\x01 \x01(\v2\x1b.types.BroadcastChatMessageH\x00R\vchatMessage\x12L\n" +
	"\x10channel_creation\x18\x02 \x01(\v2\x1f.types.BroadcastChannelCreationH\x00R\x0fchannelCreation\x12I\n" +
	"\x0fchannel_removed\x18\x03 \x01(\v2\x1e.types.BroadcastChannelRemovedH\x00R\x0echannelRemovedB\t\n" +
	"\acontent\"F\n" +
	"\fUserLinksRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"J\n" +
	"\fUserFactsRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xec\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\x06avatar\x18\x05 \x01(\tH\x00R\x06avatar\x88\x01\x01\x12\x1b\n" +
	"\x06banner\x18\x06 \x01(\tH\x01R\x06banner\x88\x01\x01\x12&\n" +
	"\fgradient_top\x18\a \x01(\tH\x02R\vgradientTop\x88\x01\x01\x12,\n" +
	"\x0fgradient_bottom\x18\b \x01(\tH\x03R\x0egradientBottom\x88\x01\x01\x12\x19\n" +
	"\x05about\x18\t \x01(\tH\x04R\x05about\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12)\n" +
	"\x05links\x18\v \x03(\v2\x13.types.UserLinksRowR\x05links\x12)\n" +
	"\x05facts\x18\f \x03(\v2\x13.types.UserFactsRowR\x05factsB\t\n" +
	"\a_avatarB\t\n" +
	"\a_bannerB\x0f\n" +
	"\r_gradient_topB\x12\n" +
	"\x10_gradient_bottomB\b\n" +
	"\x06_about\"\xe4\x01\n" +
	"\x13IncomingChatMessage\x12#\n" +
	"\x06author\x18\x01 \x01(\v2\v.types.UserR\x06author\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x05R\bserverId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\x05R\tchannelId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12%\n" +
	"\x0ementions_users\x18\x05 \x03(\x05R\rmentionsUsers\x12+\n" +
	"\x11mentions_channels\x18\x06 \x03(\x05R\x10mentionsChannels\"\xb0\x02\n" +
	"\x14BroadcastChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12#\n" +
	"\x06author\x18\x02 \x01(\v2\v.types.UserR\x06author\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\x05R\bserverId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\x05R\tchannelId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12%\n" +
	"\x0ementions_users\x18\x06 \x03(\x05R\rmentionsUsers\x12+\n" +
	"\x11mentions_channels\x18\a \x03(\x05R\x10mentionsChannels\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x95\x01\n" +
	"\x17BroadcastChannelRemoved\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\x05R\tchannelId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12#\n" +
	"\ractor_address\x18\x04 \x01(\tR\factorAddress\"\xa4\x03\n" +
	"\x18BroadcastChannelCreation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x05R\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x14\n" +
	"\x05users\x18\x06 \x03(\x05R\x05users\x12\x14\n" +
	"\x05roles\x18\a \x03(\x05R\x05roles\x12\f\n" +
	"\x01x\x18\b \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\t \x01(\x05R\x01y\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x19\n" +
	"\bactor_id\x18\f \x01(\tR\aactorId\x12#\n" +
	"\ractor_address\x18\r \x01(\tR\factorAddressB\x0e\n" +
	"\f_description\"\xe3\x01\n" +
	"\x13BodyChannelCreation\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05users\x18\x06 \x03(\x05R\x05users\x12\x14\n" +
	"\x05roles\x18\a \x03(\x05R\x05roles\x12\f\n" +
	"\x01x\x18\b \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\t \x01(\x05R\x01y\"i\n" +
	"\x12BodyChannelRemoved\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\x05R\tchannelId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"R\n" +
	"\x10NewServerCreated\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12#\n" +
	"\ractor_address\x18\x02 \x01(\tR\factorAddress\"\t\n" +
	"\aConnect\"\f\n" +
	"\n" +
	"DisconnectB\x1cZ\x1agithub.com/okzmo/nyo/protob\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_types_proto_goTypes = []any{
	(*WSMessage)(nil),                // 0: types.WSMessage
	(*UserLinksRow)(nil),             // 1: types.UserLinksRow
	(*UserFactsRow)(nil),             // 2: types.UserFactsRow
	(*User)(nil),                     // 3: types.User
	(*IncomingChatMessage)(nil),      // 4: types.IncomingChatMessage
	(*BroadcastChatMessage)(nil),     // 5: types.BroadcastChatMessage
	(*BroadcastChannelRemoved)(nil),  // 6: types.BroadcastChannelRemoved
	(*BroadcastChannelCreation)(nil), // 7: types.BroadcastChannelCreation
	(*BodyChannelCreation)(nil),      // 8: types.BodyChannelCreation
	(*BodyChannelRemoved)(nil),       // 9: types.BodyChannelRemoved
	(*NewServerCreated)(nil),         // 10: types.NewServerCreated
	(*Connect)(nil),                  // 11: types.Connect
	(*Disconnect)(nil),               // 12: types.Disconnect
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
}
var file_types_proto_depIdxs = []int32{
	5,  // 0: types.WSMessage.chat_message:type_name -> types.BroadcastChatMessage
	7,  // 1: types.WSMessage.channel_creation:type_name -> types.BroadcastChannelCreation
	6,  // 2: types.WSMessage.channel_removed:type_name -> types.BroadcastChannelRemoved
	13, // 3: types.User.created_at:type_name -> google.protobuf.Timestamp
	1,  // 4: types.User.links:type_name -> types.UserLinksRow
	2,  // 5: types.User.facts:type_name -> types.UserFactsRow
	3,  // 6: types.IncomingChatMessage.author:type_name -> types.User
	3,  // 7: types.BroadcastChatMessage.author:type_name -> types.User
	13, // 8: types.BroadcastChatMessage.created_at:type_name -> google.protobuf.Timestamp
	13, // 9: types.BroadcastChannelCreation.created_at:type_name -> google.protobuf.Timestamp
	13, // 10: types.BroadcastChannelCreation.updated_at:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	file_types_proto_msgTypes[0].OneofWrappers = []any{
		(*WSMessage_ChatMessage)(nil),
		(*WSMessage_ChannelCreation)(nil),
		(*WSMessage_ChannelRemoved)(nil),
	}
	file_types_proto_msgTypes[3].OneofWrappers = []any{}
	file_types_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
