-- migrate:up
CREATE TYPE channel_type AS ENUM ('voice', 'textual');
CREATE TYPE abilities AS ENUM ('ADMIN', 'MANAGE_CHANNELS', 'MANAGE_ROLES', 'MANAGE_SERVER', 'MANAGE_EXPRESSIONS', 'CHANGE_NICKNAME', 'MANAGE_NICKNAMES', 'BAN', 'KICK', 'MUTE', 'ATTACH_FILES', 'MANAGE_MESSAGES');

CREATE TABLE users(
  id VARCHAR(20) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  avatar VARCHAR(255),
  banner VARCHAR(255),
  about TEXT,
  gradient_top VARCHAR(255),
  gradient_bottom VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE friends(
  id VARCHAR(20) PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  friend_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  accepted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE links(
  id VARCHAR(20) PRIMARY KEY,
  user_id VARCHAR(20) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  label VARCHAR(255),
  url VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE facts(
  id VARCHAR(20) PRIMARY KEY,
  user_id VARCHAR(20) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  icon VARCHAR(255),
  label VARCHAR(255),
  value VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE servers(
  id VARCHAR(20) PRIMARY KEY,
  owner_id VARCHAR(20) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  avatar VARCHAR(255),
  banner VARCHAR(255),
  description TEXT,
  private BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE channels(
  id VARCHAR(20) PRIMARY KEY,
  server_id VARCHAR(20) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  type channel_type NOT NULL,
  description TEXT,
  users VARCHAR(20) ARRAY,
  roles VARCHAR(20) ARRAY,
  x INT NOT NULL,
  y INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE roles(
  id VARCHAR(20) PRIMARY KEY,
  server_id VARCHAR(20) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  color VARCHAR(255) NOT NULL,
  description TEXT,
  abilities TEXT ARRAY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE messages(
  id VARCHAR(20) PRIMARY KEY,
  author_id VARCHAR(20) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  server_id VARCHAR(20) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  channel_id VARCHAR(20) NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  content JSONB NOT NULL,
  mentions_users VARCHAR(20) ARRAY,
  mentions_channels VARCHAR(20) ARRAY,
  attached TEXT ARRAY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE server_membership(
  id VARCHAR(20) PRIMARY KEY,
  user_id VARCHAR(20) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  server_id VARCHAR(20) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  roles VARCHAR(20) ARRAY,
  x INT NOT NULL,
  y INT NOT NULL,
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE(user_id, server_id)
);

CREATE TABLE tokens(
  id VARCHAR(20) PRIMARY KEY,
  user_id VARCHAR(20) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  type VARCHAR(255) NOT NULL,
  expire_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE invites(
  id VARCHAR(20) PRIMARY KEY,
  server_id VARCHAR(20) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  invite_id VARCHAR(255) NOT NULL,
  expire_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_tokens_token ON tokens(token);
CREATE INDEX idx_invites_invite_id ON invites(invite_id);


INSERT INTO users
VALUES ('global', 'admin', 'admin', '', '');

INSERT INTO servers
VALUES ('global', 'global', 'global');

-- migrate:down
DROP TABLE invites;
DROP TABLE tokens;
DROP TABLE server_membership;
DROP TABLE messages;
DROP TABLE roles;
DROP TABLE channels;
DROP TABLE servers;
DROP TABLE links;
DROP TABLE facts;
DROP TABLE friends;
DROP TABLE users;
DROP TYPE channel_type;
DROP TYPE abilities;
