// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgconn"
)

const checkChannelMembership = `-- name: CheckChannelMembership :execresult
SELECT c.id FROM channels c, server_membership sm WHERE c.id = $1 and c.server_id = sm.server_id and sm.user_id = $2
`

type CheckChannelMembershipParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) CheckChannelMembership(ctx context.Context, arg CheckChannelMembershipParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, checkChannelMembership, arg.ID, arg.UserID)
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
  id, author_id, server_id, channel_id, content, mentions_users, mentions_channels, attached
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, author_id, server_id, channel_id, content, mentions_users, mentions_channels, attached, created_at, updated_at
`

type CreateMessageParams struct {
	ID               string          `json:"id"`
	AuthorID         string          `json:"author_id"`
	ServerID         string          `json:"server_id"`
	ChannelID        string          `json:"channel_id"`
	Content          json.RawMessage `json:"content"`
	MentionsUsers    []string        `json:"mentions_users"`
	MentionsChannels []string        `json:"mentions_channels"`
	Attached         []string        `json:"attached"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.AuthorID,
		arg.ServerID,
		arg.ChannelID,
		arg.Content,
		arg.MentionsUsers,
		arg.MentionsChannels,
		arg.Attached,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ServerID,
		&i.ChannelID,
		&i.Content,
		&i.MentionsUsers,
		&i.MentionsChannels,
		&i.Attached,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :execresult
DELETE FROM messages WHERE id = $1 AND author_id = $2
`

type DeleteMessageParams struct {
	ID       string `json:"id"`
	AuthorID string `json:"author_id"`
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteMessage, arg.ID, arg.AuthorID)
}

const getMessage = `-- name: GetMessage :one
SELECT id, author_id, server_id, channel_id, content, mentions_users, mentions_channels, attached, created_at, updated_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ServerID,
		&i.ChannelID,
		&i.Content,
		&i.MentionsUsers,
		&i.MentionsChannels,
		&i.Attached,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessagesFromChannel = `-- name: GetMessagesFromChannel :many
SELECT id, author_id, server_id, channel_id, content, mentions_users, mentions_channels, attached, created_at, updated_at FROM messages WHERE channel_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetMessagesFromChannel(ctx context.Context, channelID string) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesFromChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ServerID,
			&i.ChannelID,
			&i.Content,
			&i.MentionsUsers,
			&i.MentionsChannels,
			&i.Attached,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :execresult
UPDATE messages 
SET content = $1, mentions_users = $2, mentions_channels = $3, updated_at = now()
WHERE id = $4 AND author_id = $5
`

type UpdateMessageParams struct {
	Content          json.RawMessage `json:"content"`
	MentionsUsers    []string        `json:"mentions_users"`
	MentionsChannels []string        `json:"mentions_channels"`
	ID               string          `json:"id"`
	AuthorID         string          `json:"author_id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateMessage,
		arg.Content,
		arg.MentionsUsers,
		arg.MentionsChannels,
		arg.ID,
		arg.AuthorID,
	)
}

const updateMessageContent = `-- name: UpdateMessageContent :execresult
UPDATE messages SET content = $1 WHERE id = $2 AND author_id = $3
`

type UpdateMessageContentParams struct {
	Content  json.RawMessage `json:"content"`
	ID       string          `json:"id"`
	AuthorID string          `json:"author_id"`
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateMessageContent, arg.Content, arg.ID, arg.AuthorID)
}

const updateMessageMentionsChannels = `-- name: UpdateMessageMentionsChannels :execresult
UPDATE messages SET mentions_channels = $1 WHERE id = $2 AND author_id = $3
`

type UpdateMessageMentionsChannelsParams struct {
	MentionsChannels []string `json:"mentions_channels"`
	ID               string   `json:"id"`
	AuthorID         string   `json:"author_id"`
}

func (q *Queries) UpdateMessageMentionsChannels(ctx context.Context, arg UpdateMessageMentionsChannelsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateMessageMentionsChannels, arg.MentionsChannels, arg.ID, arg.AuthorID)
}

const updateMessageMentionsUsers = `-- name: UpdateMessageMentionsUsers :execresult
UPDATE messages SET mentions_users = $1 WHERE id = $2 AND author_id = $3
`

type UpdateMessageMentionsUsersParams struct {
	MentionsUsers []string `json:"mentions_users"`
	ID            string   `json:"id"`
	AuthorID      string   `json:"author_id"`
}

func (q *Queries) UpdateMessageMentionsUsers(ctx context.Context, arg UpdateMessageMentionsUsersParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateMessageMentionsUsers, arg.MentionsUsers, arg.ID, arg.AuthorID)
}
