// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (
  id, server_id, name, color, description, abilities
) VALUES (
  $1, $2, $3, $4, $5, $6
)
`

type CreateRoleParams struct {
	ID          string      `json:"id"`
	ServerID    string      `json:"server_id"`
	Name        string      `json:"name"`
	Color       string      `json:"color"`
	Description pgtype.Text `json:"description"`
	Abilities   []string    `json:"abilities"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole,
		arg.ID,
		arg.ServerID,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.Abilities,
	)
	return err
}
