// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateEmojiParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Url       string `json:"url"`
	Shortcode string `json:"shortcode"`
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, email, username, display_name, avatar, banner, body, main_color, password
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, email, username, password, display_name, avatar, banner, body, about, main_color, links, facts, experience, created_at, updated_at
`

type CreateUserParams struct {
	ID          string      `json:"id"`
	Email       string      `json:"email"`
	Username    string      `json:"username"`
	DisplayName string      `json:"display_name"`
	Avatar      pgtype.Text `json:"avatar"`
	Banner      pgtype.Text `json:"banner"`
	Body        pgtype.Text `json:"body"`
	MainColor   pgtype.Text `json:"main_color"`
	Password    string      `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.Avatar,
		arg.Banner,
		arg.Body,
		arg.MainColor,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.DisplayName,
		&i.Avatar,
		&i.Banner,
		&i.Body,
		&i.About,
		&i.MainColor,
		&i.Links,
		&i.Facts,
		&i.Experience,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmoji = `-- name: DeleteEmoji :exec
DELETE FROM emojis WHERE user_id = $1 AND id = $2
`

type DeleteEmojiParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

func (q *Queries) DeleteEmoji(ctx context.Context, arg DeleteEmojiParams) error {
	_, err := q.db.Exec(ctx, deleteEmoji, arg.UserID, arg.ID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getEmojis = `-- name: GetEmojis :many
SELECT id, url, shortcode FROM emojis WHERE user_id = $1
`

type GetEmojisRow struct {
	ID        string `json:"id"`
	Url       string `json:"url"`
	Shortcode string `json:"shortcode"`
}

func (q *Queries) GetEmojis(ctx context.Context, userID string) ([]GetEmojisRow, error) {
	rows, err := q.db.Query(ctx, getEmojis, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmojisRow
	for rows.Next() {
		var i GetEmojisRow
		if err := rows.Scan(&i.ID, &i.Url, &i.Shortcode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, email, username, password, display_name, avatar, banner, body, about, main_color, links, facts, experience, created_at, updated_at FROM users WHERE email = $1 OR username = $2
`

type GetUserParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.DisplayName,
		&i.Avatar,
		&i.Banner,
		&i.Body,
		&i.About,
		&i.MainColor,
		&i.Links,
		&i.Facts,
		&i.Experience,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, username, password, display_name, avatar, banner, body, about, main_color, links, facts, experience, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.DisplayName,
		&i.Avatar,
		&i.Banner,
		&i.Body,
		&i.About,
		&i.MainColor,
		&i.Links,
		&i.Facts,
		&i.Experience,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserMinimal = `-- name: GetUserMinimal :one
SELECT id, username, display_name, avatar FROM users WHERE id = $1
`

type GetUserMinimalRow struct {
	ID          string      `json:"id"`
	Username    string      `json:"username"`
	DisplayName string      `json:"display_name"`
	Avatar      pgtype.Text `json:"avatar"`
}

func (q *Queries) GetUserMinimal(ctx context.Context, id string) (GetUserMinimalRow, error) {
	row := q.db.QueryRow(ctx, getUserMinimal, id)
	var i GetUserMinimalRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Avatar,
	)
	return i, err
}

const getUsersByIds = `-- name: GetUsersByIds :many
SELECT id, username, display_name, avatar FROM users WHERE id = ANY($1::text[])
`

type GetUsersByIdsRow struct {
	ID          string      `json:"id"`
	Username    string      `json:"username"`
	DisplayName string      `json:"display_name"`
	Avatar      pgtype.Text `json:"avatar"`
}

func (q *Queries) GetUsersByIds(ctx context.Context, dollar_1 []string) ([]GetUsersByIdsRow, error) {
	rows, err := q.db.Query(ctx, getUsersByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByIdsRow
	for rows.Next() {
		var i GetUsersByIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmoji = `-- name: UpdateEmoji :exec
UPDATE emojis SET shortcode = $1 WHERE user_id = $2 AND id = $3
`

type UpdateEmojiParams struct {
	Shortcode string `json:"shortcode"`
	UserID    string `json:"user_id"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateEmoji(ctx context.Context, arg UpdateEmojiParams) error {
	_, err := q.db.Exec(ctx, updateEmoji, arg.Shortcode, arg.UserID, arg.ID)
	return err
}

const updateUserAbout = `-- name: UpdateUserAbout :exec
UPDATE users
  set about = $2
WHERE id = $1
`

type UpdateUserAboutParams struct {
	ID    string `json:"id"`
	About []byte `json:"about"`
}

func (q *Queries) UpdateUserAbout(ctx context.Context, arg UpdateUserAboutParams) error {
	_, err := q.db.Exec(ctx, updateUserAbout, arg.ID, arg.About)
	return err
}

const updateUserAvatarNBanner = `-- name: UpdateUserAvatarNBanner :exec
UPDATE users
  set avatar = $2, banner = $3, main_color = $4
WHERE id = $1
`

type UpdateUserAvatarNBannerParams struct {
	ID        string      `json:"id"`
	Avatar    pgtype.Text `json:"avatar"`
	Banner    pgtype.Text `json:"banner"`
	MainColor pgtype.Text `json:"main_color"`
}

func (q *Queries) UpdateUserAvatarNBanner(ctx context.Context, arg UpdateUserAvatarNBannerParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatarNBanner,
		arg.ID,
		arg.Avatar,
		arg.Banner,
		arg.MainColor,
	)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users
  set display_name = $2
WHERE id = $1
`

type UpdateUserDisplayNameParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users
  set email = $2
WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}

const updateUserFacts = `-- name: UpdateUserFacts :exec
UPDATE users
  set facts = $2
WHERE id = $1
`

type UpdateUserFactsParams struct {
	ID    string `json:"id"`
	Facts []byte `json:"facts"`
}

func (q *Queries) UpdateUserFacts(ctx context.Context, arg UpdateUserFactsParams) error {
	_, err := q.db.Exec(ctx, updateUserFacts, arg.ID, arg.Facts)
	return err
}

const updateUserLinks = `-- name: UpdateUserLinks :exec
UPDATE users
  set links = $2
WHERE id = $1
`

type UpdateUserLinksParams struct {
	ID    string `json:"id"`
	Links []byte `json:"links"`
}

func (q *Queries) UpdateUserLinks(ctx context.Context, arg UpdateUserLinksParams) error {
	_, err := q.db.Exec(ctx, updateUserLinks, arg.ID, arg.Links)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
  set password = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       string `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserUsername = `-- name: UpdateUserUsername :execresult
UPDATE users
  set username = $2
WHERE id = $1
`

type UpdateUserUsernameParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateUserUsername, arg.ID, arg.Username)
}
